name: CI-CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.get_short_sha.outputs.short_sha }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Get Short SHA
        id: get_short_sha
        run: echo "short_sha=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/python-app:${{ steps.get_short_sha.outputs.short_sha }}

  update-manifest:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Infra Repo
        uses: actions/checkout@v3
        with:
          repository: dinesh1496/infra-repo-v2
          token: ${{ secrets.INFRA_REPO_TOKEN }}
          path: infra-repo-v2

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      - name: Update Image Tag in Helm Values
        run: |
          cd infra-repo-v2
          yq -i ".image.tag = \"${{ needs.build-and-push.outputs.short_sha }}\"" helm-charts/python-app/values.yaml

      - name: Commit and Push to Infra Repo
        run: |
          cd infra-repo-v2
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploying image tag ${{ needs.build-and-push.outputs.short_sha }}" || echo "No changes to commit"
          git push origin main